import type { LearningResource } from "@/lib/resources/types";

const createdAt = new Date(0).toISOString();

export const fallbackResources: LearningResource[] = [
  {
    id: "visual-guide-to-integration-techniques",
    slug: "visual-guide-to-integration-techniques",
    title: "A visual guide to integration techniques",
    subject: "Mathematics",
    topic: "Calculus",
    level: "Undergraduate",
    type: "PDF",
    tone: "violet",
    description:
      "Clear diagrams and worked examples for substitution, parts, and partial fractions.",
    fileUrl: null,
    externalUrl: "https://example.com/resources/integration-techniques",
    saveCount: 2400,
    helpfulCount: 580,
    ratingAverage: 4.9,
    ratingCount: 182,
    createdAt,
    updatedAt: createdAt,
    isSaved: false,
    isHelpful: false,
    author: {
      id: 0,
      name: "Sarah Chen",
      username: "sarahchen",
      profilePicture: "",
    },
  },
  {
    id: "python-data-structures-reference",
    slug: "python-data-structures-reference",
    title: "Python data structures reference",
    subject: "Technology",
    topic: "Programming",
    level: "Beginner",
    type: "GUIDE",
    tone: "blue",
    description:
      "A compact reference for lists, dictionaries, sets, tuples, and common patterns.",
    fileUrl: null,
    externalUrl: "https://example.com/resources/python-data-structures",
    saveCount: 1800,
    helpfulCount: 430,
    ratingAverage: 4.8,
    ratingCount: 149,
    createdAt,
    updatedAt: createdAt,
    isSaved: false,
    isHelpful: false,
    author: {
      id: 0,
      name: "Maya Patel",
      username: "mayapatel",
      profilePicture: "",
    },
  },
  {
    id: "mechanics-problem-solving-workbook",
    slug: "mechanics-problem-solving-workbook",
    title: "Mechanics problem-solving workbook",
    subject: "Science",
    topic: "Physics",
    level: "A Level",
    type: "PDF",
    tone: "teal",
    description:
      "Practice questions with structured hints for forces, momentum, and energy.",
    fileUrl: null,
    externalUrl: "https://example.com/resources/mechanics-workbook",
    saveCount: 980,
    helpfulCount: 220,
    ratingAverage: 4.7,
    ratingCount: 91,
    createdAt,
    updatedAt: createdAt,
    isSaved: false,
    isHelpful: false,
    author: {
      id: 0,
      name: "Leo Martins",
      username: "leomartins",
      profilePicture: "",
    },
  },
  {
    id: "arduino-sensor-examples",
    slug: "arduino-sensor-examples",
    title: "Arduino sensor examples",
    subject: "Engineering",
    topic: "Electronics",
    level: "Beginner",
    type: "CODE",
    tone: "amber",
    description:
      "Reusable wiring diagrams and code examples for common environmental sensors.",
    fileUrl: null,
    externalUrl: "https://example.com/resources/arduino-sensor-examples",
    saveCount: 1500,
    helpfulCount: 390,
    ratingAverage: 4.9,
    ratingCount: 126,
    createdAt,
    updatedAt: createdAt,
    isSaved: false,
    isHelpful: false,
    author: {
      id: 0,
      name: "Robotics Club",
      username: "roboticsclub",
      profilePicture: "",
    },
  },
  {
    id: "neural-networks-from-first-principles",
    slug: "neural-networks-from-first-principles",
    title: "Neural networks from first principles",
    subject: "Technology",
    topic: "AI",
    level: "Intermediate",
    type: "VIDEO",
    tone: "blue",
    description:
      "A concept-first lesson on layers, activations, gradients, and training.",
    fileUrl: null,
    externalUrl: "https://example.com/resources/neural-networks-first-principles",
    saveCount: 3100,
    helpfulCount: 740,
    ratingAverage: 4.9,
    ratingCount: 238,
    createdAt,
    updatedAt: createdAt,
    isSaved: false,
    isHelpful: false,
    author: {
      id: 0,
      name: "Dr. James Liu",
      username: "jamesliu",
      profilePicture: "",
    },
  },
  {
    id: "biology-revision-maps",
    slug: "biology-revision-maps",
    title: "Biology revision maps",
    subject: "Science",
    topic: "Biology",
    level: "GCSE",
    type: "NOTES",
    tone: "teal",
    description:
      "Linked concept maps for cells, genetics, ecology, and human systems.",
    fileUrl: null,
    externalUrl: "https://example.com/resources/biology-revision-maps",
    saveCount: 760,
    helpfulCount: 160,
    ratingAverage: 4.6,
    ratingCount: 64,
    createdAt,
    updatedAt: createdAt,
    isSaved: false,
    isHelpful: false,
    author: {
      id: 0,
      name: "Sofia Rossi",
      username: "sofiarossi",
      profilePicture: "",
    },
  },
];
