export const reducerCases = {
  SET_USER_INFO: "SET_USER_INFO",
  SET_NEW_USER: "SET_NEW_USER",
  SET_ALL_CONTACTS_PAGE: "SET_ALL_CONTACTS_PAGE",
  CHANGE_CURRENT_CHAT_USER: "CHANGE_CURRENT_CHAT_USER",

  SET_SOCKET: "SET_SOCKET",
  SET_MESSAGES: "SET_MESSAGES",
  ADD_MESSAGE: "ADD_MESSAGE",
  SET_USER_CONTACTS: "USER_CONTACTS",

  //Group
  SET_GROUP_INFO: "SET_GROUP_INFO",
  CHANGE_CURRENT_GROUP: "CHANGE_CURRENT_GROUP",
  SET_GROUP_MESSAGES: "SET_GROUP_MESSAGES",
  ADD_GROUP_MESSAGE: "ADD_GROUP_MESSAGE",
  SET_GROUP_CONTACTS: "SET_GROUP_CONTACTS",
  SET_VOICE_CALL: "SET_VOICE_CALL",
  SET_VIDEO_CALL: "SET_VIDEO_CALL",
  END_CALL: "END_CALL",
  SET_INCOMING_VOICE_CALL: "SET_INCOMING_VOICE_CALL",
  SET_INCOMING_VIDEO_CALL: "SET_INCOMING_VIDEO_CALL",
  SET_EXIT_CHAT: "SET_EXIT_CHAT",
  SET_MESSAGES_READ: "SET_MESSAGES_READ",
  SET_ONLINE_USERS: "SET_ONLINE_USERS",
  SET_MESSAGES_SEARCH: "SET_MESSAGES_SEARCH",
  SET_CONTACT_SEARCH: "SET_CONTACT_SEARCH",
};
