# Generated by Django 4.0.3 on 2024-02-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MEhub', '0002_teacher_alter_student_options_alter_student_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='major_subject',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
