# Generated by Django 4.0.3 on 2024-02-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MEhub', '0003_teacher_major_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='bio',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
    ]
