export const careerPaths = [
  {
    title: "Software Developer",
    description: "Design, develop, and test software applications.",
    skills: ["Programming", "Problem-solving", "Algorithm design"],
    salaryRange: "$60,000 - $150,000 per year",
    growthRate: "Projected faster than average growth",
    education: "Bachelor’s degree in Computer Science or related field",
    experience: "Entry-level roles available for fresh graduates",
    workEnvironment: "Office-based, may work remotely in some cases",
    industries: [
      "Technology",
      "Software Development",
      "Information Technology",
    ],
    relatedCareers: ["Web Developer", "Data Analyst", "Software Engineer"],
    subjectsActivities: ["Coding", "Math", "Science", "Art"],
    hobbiesProjects: ["Robotics", "Game Dev", "Writing", "Cooking"],
    skills: ["Programming", "Problem-solving", "Teamwork", "Adaptability"],
    workStyle: "Both",
    workLifeBalance: "Balanced",
    goals: ["Starting a business", "Making a social impact"],
    impacts: ["Technology Ethics", "Environmental Sustainability"],
    industryPreferences: ["Tech Startups", "Non-profit"],
    longTermGoals: ["Leading a team", "Creating innovative solutions"],
    roleModels: ["Elon Musk", "Steve Jobs", "Oprah Winfrey"],
  },
  {
    title: "Registered Nurse",
    description:
      "Provide and coordinate patient care, educate patients about health conditions.",
    skills: ["Patient care", "Communication", "Medical knowledge"],
    salaryRange: "$60,000 - $110,000 per year",
    growthRate: "Projected much faster than average growth",
    education:
      "Bachelor of Science in Nursing (BSN) or Associate Degree in Nursing (ADN)",
    experience: "Clinical rotations/internships during education are common",
    workEnvironment:
      "Hospitals, clinics, nursing homes, may have flexible shifts",
    industries: ["Healthcare", "Nursing"],
    relatedCareers: [
      "Nurse Practitioner",
      "Nurse Anesthetist",
      "Nurse Educator",
    ],
    subjectsActivities: ["Science", "Math", "Art"],
    hobbiesProjects: ["Volunteering", "Gardening", "Photography"],
    skills: ["Communication", "Organization", "Adaptability"],
    workStyle: "Collaborative",
    workLifeBalance: "Balanced",
    goals: ["Advancing in a particular field", "Achieving financial stability"],
    impacts: ["Healthcare Accessibility", "Education Equality"],
    industryPreferences: ["Healthcare", "Education"],
    longTermGoals: [
      "Achieving work-life balance",
      "Exploring multiple career paths",
    ],
    roleModels: ["Malala Yousafzai", "Marie Curie", "Jeff Bezos"],
  },
  {
    title: "Marketing Manager",
    description:
      "Develop marketing strategies and campaigns for products/services.",
    skills: ["Marketing strategy", "Analytical skills", "Creativity"],
    salaryRange: "$70,000 - $150,000 per year",
    growthRate: "Projected faster than average growth",
    education:
      "Bachelor’s degree in Marketing, Business Administration or related field",
    experience: "Previous experience in marketing roles is often required",
    workEnvironment:
      "Office-based, may involve travel for meetings and campaigns",
    industries: ["Marketing", "Advertising", "Sales"],
    relatedCareers: [
      "Marketing Specialist",
      "Brand Manager",
      "Digital Marketing Manager",
    ],
    subjectsActivities: ["Literature", "History", "Music"],
    hobbiesProjects: ["Painting", "Cooking", "Gardening"],
    skills: ["Creativity", "Analytical Thinking", "Leadership"],
    workStyle: "Independent",
    workLifeBalance: "Balanced",
    goals: ["Making a social impact", "Traveling the world"],
    impacts: ["Entertainment", "Finance"],
    industryPreferences: ["Entertainment", "Finance"],
    longTermGoals: ["Achieving work-life balance", "Leading a team"],
    roleModels: ["Malala Yousafzai", "Oprah Winfrey", "Jeff Bezos"],
  },
  {
    title: "Data Scientist",
    description:
      "Analyze and interpret complex data to help organizations make data-driven decisions.",
    skills: ["Data analysis", "Statistics", "Machine learning"],
    salaryRange: "$80,000 - $160,000 per year",
    growthRate: "Projected much faster than average growth",
    education: "Master’s degree in Data Science or related field",
    experience: "Experience in data analysis or related fields is beneficial",
    workEnvironment: "Office-based, often collaborate with various departments",
    industries: ["Technology", "Finance", "Healthcare"],
    relatedCareers: ["Data Analyst", "Business Analyst", "Data Engineer"],
    subjectsActivities: ["Mathematics", "Statistics", "Computer Science"],
    hobbiesProjects: [
      "Data visualization",
      "Predictive modeling",
      "Open-source contributions",
    ],
    skills: [
      "Data analysis",
      "Programming",
      "Problem-solving",
      "Communication",
    ],
    workStyle: "Both",
    workLifeBalance: "Balanced",
    goals: ["Solving complex problems", "Driving business insights"],
    impacts: ["Technology advancement", "Business efficiency improvement"],
    industryPreferences: ["Technology", "Finance"],
    longTermGoals: [
      "Leading data-driven strategies",
      "Mentoring aspiring data scientists",
    ],
    roleModels: ["Jeff Hammerbacher", "DJ Patil", "Fei-Fei Li"],
  },
  {
    title: "Civil Engineer",
    description:
      "Design and oversee construction projects, such as buildings, bridges, and roads.",
    skills: ["Engineering design", "Project management", "Problem-solving"],
    salaryRange: "$60,000 - $120,000 per year",
    growthRate: "Projected average growth",
    education: "Bachelor’s degree in Civil Engineering",
    experience: "Internships during education can be beneficial",
    workEnvironment: "Office-based for design, fieldwork for project oversight",
    industries: ["Construction", "Engineering"],
    relatedCareers: [
      "Structural Engineer",
      "Environmental Engineer",
      "Transportation Planner",
    ],
    subjectsActivities: ["Physics", "Mathematics", "Architecture"],
    hobbiesProjects: [
      "Modeling and designing structures",
      "Sustainability projects",
      "Community volunteering",
    ],
    skills: ["Design analysis", "Project management", "Collaboration"],
    workStyle: "Independent",
    workLifeBalance: "Balanced",
    goals: [
      "Creating sustainable infrastructure",
      "Enhancing public safety through design",
    ],
    impacts: ["Community development", "Environmental sustainability"],
    industryPreferences: ["Construction", "Infrastructure development"],
    longTermGoals: [
      "Leading large-scale projects",
      "Mentoring future engineers",
    ],
    roleModels: ["Emily Warren Roebling", "Elsie Eaves", "Fazlur Rahman Khan"],
  },
  {
    title: "Graphic Designer",
    description:
      "Create visual concepts using computer software or by hand to communicate ideas that inspire, inform, and captivate consumers.",
    skills: ["Creativity", "Adobe Creative Suite", "Communication"],
    salaryRange: "$40,000 - $80,000 per year",
    growthRate: "Projected average growth",
    education: "Bachelor’s degree in Graphic Design or related field",
    experience: "Portfolio often required, internships beneficial",
    workEnvironment: "Office-based, may collaborate with clients and teams",
    industries: ["Advertising", "Digital Media", "Publishing"],
    relatedCareers: ["Art Director", "UX/UI Designer", "Illustrator"],
    subjectsActivities: ["Art", "Digital Media", "Illustration"],
    hobbiesProjects: ["Typography projects", "Brand design", "Motion graphics"],
    skills: [
      "Design proficiency",
      "Creativity",
      "Communication",
      "Attention to detail",
    ],
    workStyle: "Both",
    workLifeBalance: "Balanced",
    goals: [
      "Creating impactful visual communication",
      "Staying updated with design trends",
    ],
    impacts: ["Visual storytelling", "Brand identity creation"],
    industryPreferences: ["Advertising agencies", "Design studios"],
    longTermGoals: ["Art direction roles", "Mentoring budding designers"],
    roleModels: ["Milton Glaser", "Paula Scher", "David Carson"],
  },
  {
    title: "Financial Analyst",
    description:
      "Analyze financial information to help companies make informed decisions about their investments.",
    skills: ["Financial analysis", "Risk management", "Data interpretation"],
    salaryRange: "$60,000 - $120,000 per year",
    growthRate: "Projected faster than average growth",
    education:
      "Bachelor’s degree in Finance, Accounting, Economics, or related field",
    experience: "Internships or related experience beneficial",
    workEnvironment: "Office-based, interact with various departments",
    industries: ["Finance", "Consulting", "Banking"],
    relatedCareers: ["Investment Analyst", "Business Analyst", "Risk Analyst"],
    subjectsActivities: ["Finance", "Economics", "Accounting"],
    hobbiesProjects: [
      "Financial modeling",
      "Investment research",
      "Market analysis",
    ],
    skills: [
      "Financial analysis",
      "Problem-solving",
      "Attention to detail",
      "Communication",
    ],
    workStyle: "Independent",
    workLifeBalance: "Balanced",
    goals: [
      "Providing valuable financial insights",
      "Evolving with market trends",
    ],
    impacts: ["Smart investment decisions", "Business growth strategies"],
    industryPreferences: ["Financial firms", "Consulting agencies"],
    longTermGoals: ["Senior financial roles", "Mentoring future analysts"],
    roleModels: ["Warren Buffett", "Sallie Krawcheck", "Ray Dalio"],
  },
  {
    title: "Teacher",
    description:
      "Educate students at various levels to help them learn and apply concepts in different subjects.",
    skills: ["Teaching", "Patience", "Classroom management"],
    salaryRange: "$40,000 - $60,000 per year",
    growthRate: "Projected average growth",
    education:
      "Bachelor’s degree in Education or specific subject, teaching certification",
    experience: "Internships, student teaching, or volunteering helpful",
    workEnvironment: "Classroom-based, interact with students and faculty",
    industries: ["Education", "Public Sector"],
    relatedCareers: [
      "School Administrator",
      "Educational Consultant",
      "Curriculum Developer",
    ],
    subjectsActivities: ["Education", "Subject expertise", "Pedagogy"],
    hobbiesProjects: [
      "Lesson planning",
      "Student engagement activities",
      "Education advocacy",
    ],
    skills: [
      "Adaptability",
      "Effective communication",
      "Empathy",
      "Classroom management",
    ],
    workStyle: "Collaborative",
    workLifeBalance: "Balanced",
    goals: ["Fostering a love for learning", "Inspiring students' success"],
    impacts: ["Shaping future generations", "Education equality"],
    industryPreferences: ["Schools", "Education NGOs"],
    longTermGoals: [
      "Education leadership roles",
      "Education policy contributions",
    ],
    roleModels: ["Jaime Escalante", "Maria Montessori", "Geoffrey Canada"],
  },
  {
    title: "Physician",
    description:
      "Diagnose and treat injuries or illnesses, prescribe medications, and provide medical advice to patients.",
    skills: ["Medical knowledge", "Problem-solving", "Empathy"],
    salaryRange: "$200,000 - $400,000+ per year",
    growthRate: "Projected much faster than average growth",
    education: "Doctor of Medicine (MD) or Doctor of Osteopathic Medicine (DO)",
    experience: "Residency training and licensure required",
    workEnvironment: "Hospital-based, may have own practice",
    industries: ["Healthcare", "Medicine"],
    relatedCareers: ["Surgeon", "Pediatrician", "Psychiatrist"],
    subjectsActivities: ["Biology", "Chemistry", "Anatomy"],
    hobbiesProjects: [
      "Medical research",
      "Volunteering in healthcare",
      "Continuing medical education",
    ],
    skills: [
      "Critical thinking",
      "Decision-making",
      "Attention to detail",
      "Interpersonal skills",
    ],
    workStyle: "Career Focused",
    workLifeBalance: "Balanced",
    goals: ["Improving patient health outcomes", "Advancing medical research"],
    impacts: ["Improving healthcare access", "Advancing medical technology"],
    industryPreferences: ["Hospitals", "Private practice"],
    longTermGoals: [
      "Medical leadership roles",
      "Medical education and mentoring",
    ],
    roleModels: [
      "Dr. Anthony Fauci",
      "Dr. Paul Farmer",
      "Dr. Helen Brooke Taussig",
    ],
  },
  {
    title: "Mechanical Engineer",
    description: "Design and develop mechanical systems, tools, and devices.",
    skills: ["Mechanical design", "Problem-solving", "CAD software"],
    salaryRange: "$65,000 - $120,000 per year",
    growthRate: "Projected average growth",
    education: "Bachelor’s degree in Mechanical Engineering",
    experience: "Internships during education beneficial",
    workEnvironment: "Office-based for design, may involve fieldwork",
    industries: ["Manufacturing", "Engineering"],
    relatedCareers: [
      "Automotive Engineer",
      "Aerospace Engineer",
      "Robotics Engineer",
    ],
    subjectsActivities: ["Physics", "Mathematics", "Engineering Design"],
    hobbiesProjects: ["Product design", "Prototyping", "DIY projects"],
    skills: [
      "Mechanical design",
      "Analytical skills",
      "Problem-solving",
      "Project management",
    ],
    workStyle: "Independent",
    workLifeBalance: "Balanced",
    goals: [
      "Innovative product development",
      "Advancing engineering solutions",
    ],
    impacts: ["Technology advancement", "Product efficiency improvement"],
    industryPreferences: ["Manufacturing firms", "Engineering consulting"],
    longTermGoals: [
      "Leading large engineering projects",
      "Mentoring future engineers",
    ],
    roleModels: ["Stephanie Kwolek", "Elon Musk", "Henry Ford"],
  },
  {
    title: "Psychologist",
    description:
      "Study mental processes and human behavior, providing therapy and counseling to individuals.",
    skills: ["Therapy", "Psychological assessment", "Empathy"],
    salaryRange: "$50,000 - $110,000 per year",
    growthRate: "Projected faster than average growth",
    education: "Doctoral degree in Psychology (Ph.D. or Psy.D.)",
    experience: "Clinical experience and licensure required",
    workEnvironment: "Private practice, hospitals, clinics",
    industries: ["Healthcare", "Mental Health"],
    relatedCareers: ["Clinical Psychologist", "Counselor", "Psychiatrist"],
    subjectsActivities: ["Psychology", "Sociology", "Behavioral Science"],
    hobbiesProjects: [
      "Research studies",
      "Community outreach programs",
      "Mental health advocacy",
    ],
    skills: ["Counseling", "Research skills", "Empathy", "Communication"],
    workStyle: "Balanced",
    workLifeBalance: "Balanced",
    goals: ["Improving mental health", "Reducing stigma around mental illness"],
    impacts: ["Mental wellness promotion", "Mental health awareness"],
    industryPreferences: ["Private practice", "Healthcare facilities"],
    longTermGoals: [
      "Mental health policy contributions",
      "Mentoring future psychologists",
    ],
    roleModels: ["Sigmund Freud", "Carl Rogers", "Elizabeth Loftus"],
  },
  {
    title: "Electrician",
    description:
      "Install, maintain, and repair electrical systems in various settings.",
    skills: [
      "Electrical wiring",
      "Troubleshooting",
      "Attention to safety codes",
    ],
    salaryRange: "$40,000 - $80,000 per year",
    growthRate: "Projected average growth",
    education: "Apprenticeship, vocational training, or associate degree",
    experience: "Apprenticeship or on-the-job training required",
    workEnvironment: "Varies (construction sites, buildings, residential)",
    industries: ["Construction", "Maintenance"],
    relatedCareers: [
      "Electrical Engineer",
      "Maintenance Technician",
      "Industrial Electrician",
    ],
    subjectsActivities: ["Electrical Engineering", "Physics", "Construction"],
    hobbiesProjects: [
      "DIY electrical projects",
      "Safety compliance education",
      "Community service",
    ],
    skills: [
      "Electrical systems",
      "Problem-solving",
      "Attention to safety",
      "Technical skills",
    ],
    workStyle: "Independent",
    workLifeBalance: "Balanced",
    goals: [
      "Ensuring electrical safety",
      "Contributing to construction projects",
    ],
    impacts: ["Infrastructure safety", "Construction efficiency"],
    industryPreferences: ["Construction firms", "Maintenance services"],
    longTermGoals: ["Business ownership", "Mentoring aspiring electricians"],
    roleModels: ["Nikola Tesla", "Thomas Edison", "Margaret Ingels"],
  },
  {
    title: "Architect",
    description:
      "Design buildings and structures, considering aesthetics, functionality, and safety.",
    skills: ["Architectural design", "CAD software", "Project management"],
    salaryRange: "$60,000 - $120,000 per year",
    growthRate: "Projected average growth",
    education: "Bachelor’s or Master’s degree in Architecture",
    experience: "Internships or apprenticeships during education",
    workEnvironment:
      "Office-based for design, site visits for project oversight",
    industries: ["Architecture", "Construction"],
    relatedCareers: [
      "Urban Planner",
      "Landscape Architect",
      "Interior Designer",
    ],
    subjectsActivities: ["Architecture", "Design", "Mathematics"],
    hobbiesProjects: [
      "Architectural modeling",
      "Sustainability design",
      "Community projects",
    ],
    skills: [
      "Design proficiency",
      "Project management",
      "Collaboration",
      "Attention to detail",
    ],
    workStyle: "Both",
    workLifeBalance: "Balanced",
    goals: ["Creating innovative structures", "Sustainable architecture"],
    impacts: ["Urban development", "Aesthetic enhancement"],
    industryPreferences: ["Architectural firms", "Design agencies"],
    longTermGoals: [
      "Architectural leadership roles",
      "Mentoring young architects",
    ],
    roleModels: ["Frank Lloyd Wright", "Zaha Hadid", "Norman Foster"],
  },
  // Add more career paths as needed
];
